#!/usr/bin/env python3
import re

sum = 0

with open ("sample.txt") as file:

    for line in file:   # Traversing file line by line
        result = re.findall('[0-9]+', line)
        #a list with name result will be generated by findall method


        for num in result:    #parsing through list 
            sum += int(num)   #adding the numbers after converting them to integer from string


print(sum)
